#Название Workflow
name: CI1

# Запуск при:
on:         
  #push в ветку main
  push:
    branches: [ "main" ]  
  #pull request в ветку main
  pull_request:
    branches: [ "main" ]
  #При ручном запуске в GitHub
  workflow_dispatch:

#Выполняется одна job build
jobs:
  build:
    #С помощью matrix система автоматически создаст ещё одну
    #отдельную job. Одна для windows, другая для linux
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    #Клонирую репозиторий в runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #Увеличиваем версию
      - name: Bump patch version
        id: bump
        run: |
          CURRENT=$(cat VERSION)
          NEW=$((CURRENT + 1))
          echo "$NEW" > VERSION
          echo "new_version=$NEW" >> $GITHUB_OUTPUT
        shell: bash

      #Клонирую vcpkg для последующей сборки Boost
      - name: Clone vcpkg (Windows)
        if: matrix.os == 'windows-latest'
        #Проверка на существование папки, если нет клонирую
        run: | 
          if not exist C:\vcpkg git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
        shell: cmd

      - name: Clone vcpkg (Linux)
        if: matrix.os == 'ubuntu-latest'
        #Проверка на существование папки, если нет клонирую
        run: |
          if [ ! -d "$HOME/vcpkg" ]; then
            git clone https://github.com/microsoft/vcpkg.git $HOME/vcpkg
          fi
        shell: bash

      # Bootstrap vcpkg
      - name: Bootstrap vcpkg (Windows)
        if: matrix.os == 'windows-latest'
        run: C:\vcpkg\bootstrap-vcpkg.bat
        shell: cmd

      - name: Bootstrap vcpkg (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: $HOME/vcpkg/bootstrap-vcpkg.sh
        shell: bash

      # Подключаю лкружение компилятора Microsoft Visual C++
      - name: Setup MSVC environment (Windows only)
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      #Кэширование vcpkg
      - name: Cache vcpkg binary archives and downloads
        uses: actions/cache@v4
        with:
          path: |
            ${{ matrix.os == 'windows-latest' && 'C:\Users\runneradmin\AppData\Local\vcpkg\archives' || '/home/runner/.cache/vcpkg/archives' }}
            ${{ matrix.os == 'windows-latest' && 'C:\vcpkg\downloads' || '/home/runner/vcpkg\downloads' }}
          key: vcpkg-boost-${{ matrix.os }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            vcpkg-boost-${{ matrix.os }}-

      # Linux: build tools for libb2
      - name: Install build tools for libb2 (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf autoconf-archive automake libtool
        shell: bash

      #Устанавливаю библиотеку Boost через vcpkg
      - name: Install Boost via vcpkg (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          $env:VCPKG_ROOT = "C:\vcpkg"
          & "C:\vcpkg\vcpkg.exe" install boost:x64-windows
        shell: pwsh

      - name: Install Boost via vcpkg (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          export VCPKG_ROOT="$HOME/vcpkg"
          "$HOME/vcpkg/vcpkg" install boost:x64-linux
        shell: bash

      #Запуск конфигурации CMake
      - name: Configure with CMake (Windows)
        if: matrix.os == 'windows-latest'
        #Указываю через cmake -B директорию для сборки
        #-DCMAKE_TOOLCHAIN_FILE подключает файл toolchain от vcpkg. Этот файл заставляет CMake искать зависимости через vcpkg, а не системные пакеты.
        run: |
          $env:VCPKG_ROOT = "C:\vcpkg"
          cmake -B build -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake"
        shell: pwsh

      - name: Configure with CMake (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          export VCPKG_ROOT="$HOME/vcpkg"
          cmake -B build -DCMAKE_TOOLCHAIN_FILE="$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake"
        shell: bash

      #Сборка
      - name: Build with CMake (Windows)
        if: matrix.os == 'windows-latest'
        run: cmake --build build --config Release
        shell: pwsh

      - name: Build with CMake (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: cmake --build build
        shell: bash

      #Копирование DLL Boost
      - name: Copy Boost DLLs (Windows only)
        if: matrix.os == 'windows-latest'
        run: |
          $boostBin = "C:\vcpkg\installed\x64-windows\bin"
          $buildDir = "build\Release"
          Copy-Item "$boostBin\boost_unit_test_framework*.dll" -Destination $buildDir -Force
        shell: pwsh

      #Создание релизных артефактов (перекладываем результаты сборки в чистую папку)
      - name: Create release artifacts (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          export VCPKG_ROOT="$HOME/vcpkg"
          mkdir -p release
          cmake --install build --prefix ./release
        shell: bash

      - name: Create release artifacts (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          $env:VCPKG_ROOT = "C:\vcpkg"
          New-Item -ItemType Directory -Force -Path C:\release
          cmake --install build --config Release --prefix C:\release
        shell: pwsh

      #Загрузка артефактов на GitHub
      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-release
          path: ${{ matrix.os == 'windows-latest' && 'C:\\release' || './release' }}
          retention-days: 7
      
      #Коммит новой версии в репозиторий
      - name: Commit new version
        if: success() && matrix.os == 'ubuntu-latest'
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "CI Bot"
          git add VERSION
          git commit -m "Bump patch version to ${{ steps.bump.outputs.new_version }}"
          git push